workflows:
  ios-unsigned-workflow:
    name: iOS Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "FrameExtractionTool.xcodeproj"
        XCODE_SCHEME: "FrameExtractionTool"
        BUNDLE_ID: "caspernyong.FrameExtractionTool.CMTest"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods sources
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping CocoaPods installation"
          fi
      - name: Build unsigned archive
        script: |
          set -e
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "build/FrameExtractionTool.xcarchive" \
            archive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
      - name: Create unsigned IPA
        script: |
          set -e
          mkdir -p build/Payload
          cp -r "build/FrameExtractionTool.xcarchive/Products/Applications/FrameExtractionTool.app" "build/Payload/"
          cd build
          zip -r "FrameExtractionTool-unsigned.ipa" "Payload/"
          ls -la FrameExtractionTool-unsigned.ipa
      - name: Verify IPA structure
        script: |
          cd build
          unzip -l FrameExtractionTool-unsigned.ipa | head -20
    artifacts:
      - build/FrameExtractionTool-unsigned.ipa
      - build/FrameExtractionTool.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - casperong@example.com # Update with your email
        notify:
          success: true
          failure: true

  ios-release-workflow:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      vars:
        XCODE_WORKSPACE: "FrameExtractionTool.xcodeproj"
        XCODE_SCHEME: "FrameExtractionTool"
        BUNDLE_ID: "caspernyong.FrameExtractionTool.CMTest"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods sources
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping CocoaPods installation"
          fi
      - name: Build unsigned archive for release
        script: |
          set -e
          # Get version from git tag
          VERSION=${CM_TAG#v}
          echo "Building release version: $VERSION"
          
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "build/FrameExtractionTool-$VERSION.xcarchive" \
            archive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
      - name: Create unsigned release IPA
        script: |
          set -e
          VERSION=${CM_TAG#v}
          mkdir -p build/Payload
          cp -r "build/FrameExtractionTool-$VERSION.xcarchive/Products/Applications/FrameExtractionTool.app" "build/Payload/"
          cd build
          zip -r "FrameExtractionTool-$VERSION-unsigned.ipa" "Payload/"
          ls -la FrameExtractionTool-$VERSION-unsigned.ipa
      - name: Verify release IPA structure
        script: |
          cd build
          VERSION=${CM_TAG#v}
          unzip -l "FrameExtractionTool-$VERSION-unsigned.ipa" | head -20
    artifacts:
      - build/FrameExtractionTool-*-unsigned.ipa
      - build/FrameExtractionTool-*.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - casper@casperong.eu.org # Update with your email
        notify:
          success: true
          failure: true
